version: "3.3"
services:
  machine_learning:
      build: .
      stdin_open: true 
      tty: true     
      volumes:
        - ${DATA_DIR}:/storage
        - .:/code
      ports:
        - ${NOTEBOOK_PORT}:${NOTEBOOK_PORT}
        - ${TENSORBOARD_PORT}:${TENSORBOARD_PORT}
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]

  label_studio:
      image: heartexlabs/label-studio:1.9.1
      stdin_open: true 
      tty: true
      user: root 
      volumes:
        - ${DATA_DIR}:/storage
        - ${DATA_DIR}:/label-studio/files
        - ${LABELSTUDIO_DIR}:/label-studio/data
        - .:/code
      environment:
        - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
        - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files/
        - LOCAL_FILES_SERVING_ENABLED=true
        - LOCAL_FILES_DOCUMENT_ROOT=/label-studio/data/
      ports:
        - ${LABELSTUDIO_PORT}:${LABELSTUDIO_PORT}






