version: "3.3"
services:
  ml_deployment:
      build: .
      stdin_open: true 
      tty: true     
      volumes:
        - .:/code
      ports:
        - ${NOTEBOOK_PORT}:${NOTEBOOK_PORT}
        - ${DB_PORT}:${DB_PORT}
      cap_add:
        - SYS_ADMIN
      devices:
        - /dev/fuse
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]








